spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: aws, redis, db
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
#logging:
#  level:
#    org:
#      apache:
#        coyote:
#          http11: debug