spring:
  profiles:
    include: oauth, aws, redis, db, mail

  jpa:
    hibernate:
      ddl-auto: create
      use_sql_comments: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


