spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tripong?serverTimezone=Asia/Seoul
    username: tripong
    password: t1234

  jpa:
    hibernate:
      ddl-auto: create
      use_sql_comments: true
    properties:
      hibernate:
        format_sql: true


  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false3
  thymeleaf:
    cache: false

  messages:
    basename: messages, errors
1

logging.level:
  org.hibernate.SQL: debug