spring:
  profiles:
    include: oauth, aws, redis, db, mail, ssl

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
        default_batch_fetch_size: 500
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
#logging:
#  level:
#    org:
#      apache:
#        coyote:
#          http11: debug
#sql:
#  init:
#    mode: always
#main:
#  allow-bean-definition-overriding: true